<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
class VillagerSeeder extends Seeder
{
   
    public function run()
    {
        // php artisan db:seed --class=VillagerSeeder

        DB::table('saving_types')->insert([
            [ 'saving_type_name' => 'Deposit','saving_type_desc' => 'Deposit/pendanaan', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'saving_type_name' => 'PayLater','saving_type_desc' => 'Penagihan', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
        ]);
        DB::table('saving_segments')->insert([
            [ 'saving_segment_name' => 'Deposit A','limit_amount' => 1000000,'saving_type_id' =>1, 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'saving_segment_name' => 'Deposit B','limit_amount' => 500000,'saving_type_id' =>1, 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'saving_segment_name' => 'PayLater A','limit_amount' => 100000,'saving_type_id' =>2, 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
        ]);

        // Product Types
        DB::table('product_types')->insert([
            [ 'product_type_name' => 'PAYMENT', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_type_name' => 'PURCHASE', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
        ]);

        // Product Categories
        DB::table('product_categories')->insert([
            [ 'product_category_name' => 'PULSA', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_category_name' => 'BPJS', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_category_name' => 'PDAM', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_category_name' => 'PBB', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_category_name' => 'MULTIFINANCE', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_category_name' => 'PLN', 'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
        ]);

        // Product References
        DB::table('product_references')->insert([
            [ 'product_reference_name' => "TELKOMSEL",'product_reference_code' => "TSEL",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "INDOSAT",'product_reference_code' => "ISAT",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "THREE",'product_reference_code' => "THREE",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "AXIS",'product_reference_code' => "AXIS",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "SMARTFREN",'product_reference_code' => "SMART",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "XL",'product_reference_code' => "XL",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "BY.U",'product_reference_code' => "BYU",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "BPJS KESEHATAN",'product_reference_code' => "BPJSKS",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "PLN POSTPAID",'product_reference_code' => "PLNPOST",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            [ 'product_reference_name' => "PLN PREPAID",'product_reference_code' => "PLNPRE",  'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
        ]);
        DB::table('product_helpers')->insert([
            ['product_prefix'=>"08140",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08141",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08142",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08143",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08144",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08145",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08146",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08147",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08148",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08149",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08150",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08151",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08152",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08153",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08154",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08155",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08156",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08157",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08158",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08159",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08160",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08161",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08162",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08163",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08164",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08165",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08166",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08167",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08168",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08169",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08550",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08551",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08552",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08553",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08554",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08555",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08556",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08557",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08558",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08559",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08560",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08561",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08562",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08563",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08564",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08565",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08566",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08567",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08568",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08569",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08570",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08571",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08572",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08573",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08574",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08575",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08576",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08577",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08578",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08579",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08580",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08581",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08582",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08583",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08584",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08585",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08586",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08587",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08588",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08589",'product_reference_id'=>2,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08170",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08171",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08172",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08173",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08174",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08175",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08176",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08177",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08178",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08179",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08180",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08181",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08182",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08183",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08184",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08185",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08186",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08187",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08188",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08189",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08190",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08191",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08192",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08193",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08194",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08195",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08196",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08197",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08198",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08199",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08590",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08591",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08592",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08593",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08594",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08595",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08596",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08597",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08598",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08599",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08780",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08781",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08782",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08783",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08784",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08785",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08786",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08787",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08788",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08789",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08770",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08771",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08772",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08773",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08774",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08775",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08776",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08777",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08778",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08779",'product_reference_id'=>6,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08380",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08381",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08382",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08383",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08384",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08385",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08386",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08387",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08388",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08389",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>"08370",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08371",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08372",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08373",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08374",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08375",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08376",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08377",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08378",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08379",'product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            ['product_prefix'=>'08310','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08311','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08312','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08313','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08314','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08315','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08316','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08317','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08318','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08319','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08320','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08321','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08322','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08323','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08324','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08325','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08326','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08327','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08328','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08329','product_reference_id'=>4,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08120','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08121','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08122','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08123','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08124','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08125','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08126','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08127','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08128','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08129','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08130','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08131','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08132','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08133','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08134','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08135','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08136','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08137','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08138','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08139','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08520','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08521','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08522','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08523','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08524','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08525','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08526','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08527','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08528','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08529','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08530','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08531','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08532','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08533','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08534','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08535','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08536','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08537','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08538','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08539','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08210','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08211','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08212','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08213','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08214','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08215','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08216','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08217','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08218','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08219','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08230','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08231','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08232','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08233','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08234','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08235','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08236','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08237','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08238','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08239','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08220','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08221','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08222','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08223','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08224','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08225','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08226','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08227','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08228','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08229','product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08810','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08811','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08812','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08813','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08814','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08815','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08816','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08817','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08818','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08819','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08820','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08821','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08822','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08823','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08824','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08825','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08826','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08827','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08828','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08829','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08830','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08831','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08832','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08833','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08834','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08835','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08836','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08837','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08838','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08839','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08840','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08841','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08842','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08843','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08844','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08845','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08846','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08847','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08848','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08849','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08850','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08851','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08852','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08853','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08854','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08855','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08856','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08857','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08858','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08859','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08860','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08861','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08862','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08863','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08864','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08865','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08866','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08867','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08868','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08869','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08870','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08871','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08872','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08873','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08874','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08875','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08876','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08877','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08878','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08879','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08880','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08881','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08882','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08883','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08884','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08885','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08886','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08887','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08888','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08889','product_reference_id'=>5,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08960','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08961','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08962','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08963','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08964','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08965','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08966','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08967','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08968','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08969','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08970','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08971','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08972','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08973','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08974','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08975','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08976','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08977','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08978','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08979','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08980','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08981','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08982','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08983','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08984','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08985','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08986','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08987','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08988','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08989','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08990','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08991','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08992','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08993','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08994','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08995','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08996','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08997','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08998','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08999','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08950','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08951','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08952','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08953','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08954','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08955','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08956','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08957','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08958','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>'08959','product_reference_id'=>3,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],

            // ['product_prefix'=>"0851",'product_reference_id'=>1,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            
            ['product_prefix'=>"08510",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08511",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08512",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08513",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08514",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08515",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08516",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08517",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08518",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
            ['product_prefix'=>"08519",'product_reference_id'=>7,'created_by' => 'sys', 'created_at' =>now(), 'updated_by' => 'sys', 'updated_at' =>now()],
        ]);

    }
}
