package configs

var (
	//status code worker/helper
	WORKER_SUCCESS_CODE = "000"
	WORKER_PENDING_CODE = "500"

	WORKER_FAILED_CODE      = "900"
	WORKER_INVALID_PARAM    = "910"
	WORKER_CREDENTIAL_ERROR = "920"
	WORKER_VALIDATION_ERROR = "930"
	WORKER_SYSTEM_ERROR     = "940"
	WORKER_UNDEFINED_ERROR  = "950"
	// WORKER_VALIDATE_SYSTEM   = "090"
	BILLER_DISRUPTION         = "960"
	WORKER_BILL_NOTFOUND_CODE = "970"
)
var ( //application response code
	SUCCESS_CODE = "00"
	PENDING_CODE = "05"
	FAILED_CODE  = "09"

	INQUIRY_SUCCESS_CODE = "10"
	INQUIRY_PENDING_CODE = "15"
	INQUIRY_FAILED_CODE  = "19"

	VALIDATE_ERROR_CODE = "34"
)
var ( //application response desc
	SUCCESS_MSG = "SUCCESS"
	PENDING_MSG = "PENDING"
	FAILED_MSG  = "FAILED"

	BILLER_DISRUPTION_MSG = "BILLER DISRUPTION"
	BILL_NOTFOUND_MSG     = "BILL NOT FOUND"
	BIIL_PAID_MSG         = "SUDAH TERBAYAR"
	UNDEFINED_MSG         = "UNDEFINED"
)
